on:
  - push

env:
  TAG: v1.0.0

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu:${{ env.TAG }}
  replace_tag:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install replace_image_tag repository
        run: |
          git clone https://github.com/nayuta-ai/replace_image_tag.git
          cd replace_image_tag
          git checkout 1.0.0
          go mod tidy
          go run . -tag ${{ env.TAG }} -token ${{ secrets.TOKEN }}
